fieldLayouts:
  9d488060-499f-4e76-9e81-b77721ebe4a5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d80ddf46-4bb6-42e6-8646-133b800ddfab
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a969efe9-b5c3-472e-afa9-d2d434374efa
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: 95eb0310-c396-428e-b23a-bb3824ea2945
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
