defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  7dd7c916-7aec-40b8-b33c-b44cc22cfe48: # nft-preview-card-component
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
